"""
app/captcha_grid.py
────────────────────
Image-selection CAPTCHA (reCAPTCHA v2 style) generation and verification.

SECURITY NOTE — URL opacity:
  Grid tiles are NEVER served at a URL that contains the category name.
  Clients receive opaque URLs:  /captcha-image/{session_id}/{tile_index}
  The server maps (session_id, tile_index) → actual file path internally.
  Category information is only stored in the DB session row and only
  read server-side at verification time.

Image index:
  Loaded once at startup from data/index.json (generated by
  scripts/download_dataset.py or scripts/build_index.py).
  Format: [{"path": "images/bus/img_0001.jpg", "categories": ["bus"]}, ...]
  Paths are relative to the data/ directory.
"""

import json
import random
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Optional

from sqlmodel import Session

from app.config import get_settings
from app.db import CaptchaSession, purge_expired_sessions

settings = get_settings()

# ── Image index — loaded once at module import ────────────────────────────────
# This is the server-side index that maps file paths to categories.
# It is NEVER sent to the client in any form.

_index: list[dict] = []
_by_category: dict[str, list[dict]] = {}
_neg_by_category: dict[str, list[dict]] = {}


def _load_index() -> None:
    """Load data/index.json into memory and precompute category sets."""
    global _index, _by_category, _neg_by_category

    index_path: Path = settings.index_path
    if not index_path.exists():
        print(
            f"[captcha_grid] WARNING: {index_path} not found. "
            "Run scripts/download_dataset.py or scripts/build_index.py first."
        )
        _index = []
        _by_category = {}
        _neg_by_category = {}
        return

    _index = json.loads(index_path.read_text())

    _by_category = {}
    for item in _index:
        for cat in item.get("categories", []):
            _by_category.setdefault(cat, []).append(item)

    _neg_by_category = {
        cat: [item for item in _index if cat not in item.get("categories", [])]
        for cat in settings.grid_categories
    }

    total = len(_index)
    counts = {cat: len(imgs) for cat, imgs in _by_category.items()}
    print(f"[captcha_grid] Loaded {total} images: {counts}")


# ── Public API ────────────────────────────────────────────────────────────────

def get_available_categories() -> list[str]:
    """Return categories that have enough images to form a grid."""
    global _index
    if not _index and settings.index_path.exists():
        _load_index()

    min_needed = settings.grid_min_pos  # at least this many positives
    return [
        cat for cat in settings.grid_categories
        if len(_by_category.get(cat, [])) >= min_needed
    ]


# Auto-load on import if index file exists
if settings.index_path.exists():
    _load_index()


def generate_grid_captcha(target_category: Optional[str] = None) -> dict:
    """
    Build a grid challenge.

    Args:
        target_category: If None, chosen randomly from available categories.

    Returns:
        {
            "target_category": str,
            "instruction": str,
            "tiles": [{"path": str, "categories": [str]}, ...],
            "correct_indices": [int, ...]
        }

    Raises:
        ValueError: if no images are available.
    """
    available = get_available_categories()
    if not available:
        raise ValueError(
            "No images in the dataset. Run scripts/download_dataset.py first."
        )

    if target_category is None or target_category not in available:
        target_category = random.choice(available)

    positives = _by_category.get(target_category, [])
    # O(1) precomputed negatives lookup with fallback
    negatives = _neg_by_category.get(target_category) or [
        item for item in _index
        if target_category not in item.get("categories", [])
    ]

    n_pos = random.randint(settings.grid_min_pos, settings.grid_max_pos)
    n_neg = settings.grid_size - n_pos

    if len(positives) < n_pos:
        n_pos = len(positives)
        n_neg = settings.grid_size - n_pos
    if len(negatives) < n_neg:
        raise ValueError(
            f"Not enough negative images for category '{target_category}'. "
            "Run scripts/download_dataset.py to get more images."
        )

    chosen_pos = random.sample(positives, n_pos)
    chosen_neg = random.sample(negatives, n_neg)

    tiles = chosen_pos + chosen_neg
    random.shuffle(tiles)

    correct_indices = [
        i for i, tile in enumerate(tiles)
        if target_category in tile.get("categories", [])
    ]

    # Human-friendly category names for the instruction text
    display_name = target_category.replace("_", " ")

    return {
        "target_category": target_category,
        "instruction": f"Select all images with a {display_name}",
        "tiles": tiles,               # server-side only, stored in session JSON
        "correct_indices": correct_indices,
    }


def create_grid_session(
    db: Session,
    target_category: Optional[str] = None,
    user_id: Optional[int] = None,
) -> CaptchaSession:
    """
    Generate a grid challenge, persist it, and return the session row.

    The full tile list (paths + categories) is stored as JSON in
    captcha_answer so verification doesn't need to re-query the index.
    correct_indices are NOT stored separately — they are re-derived from
    the stored tile list at verify time using the target_category.
    """
    purge_expired_sessions(db)

    challenge = generate_grid_captcha(target_category)

    # Store the instruction and tiles; correct_indices are derived on verify
    answer_payload = json.dumps(
        {
            "target_category": challenge["target_category"],
            "instruction": challenge["instruction"],
            "tiles": challenge["tiles"],   # list of {path, categories}
        }
    )

    expires_at = datetime.now(timezone.utc) + timedelta(
        seconds=settings.captcha_ttl_seconds
    )
    session = CaptchaSession(
        user_id=user_id,
        captcha_type="grid",
        captcha_answer=answer_payload,
        expires_at=expires_at,
    )
    db.add(session)
    db.commit()
    db.refresh(session)
    return session


def get_tile_path(session_id: str, tile_index: int, db: Session) -> Optional[Path]:
    """
    Resolve (session_id, tile_index) → absolute file path for streaming.
    Returns None if session not found, expired, or index out of range.
    Category is never surfaced to the caller.
    """
    now = datetime.now(timezone.utc)
    session = db.get(CaptchaSession, session_id)
    if session is None or session.captcha_type != "grid":
        return None
    if session.expires_at.replace(tzinfo=timezone.utc) < now:
        return None

    payload = json.loads(session.captcha_answer)
    tiles = payload.get("tiles", [])
    if tile_index < 0 or tile_index >= len(tiles):
        return None

    # Path is relative to data/ dir — enforce strict directory containment
    rel_path = tiles[tile_index]["path"]
    abs_path = (settings.data_dir / rel_path).resolve()
    try:
        abs_path.relative_to(settings.data_dir.resolve())
    except ValueError:
        return None
    return abs_path if abs_path.exists() else None


def verify_grid(
    session_id: str,
    selected_indices: list[int],
    db: Session,
) -> dict:
    """
    Validate submitted tile indices against the stored correct set.

    Returns:
        {
            "success": bool,
            "correct_indices": [int, ...],   # always returned for analysis
            "instruction": str,
        }

    Session is deleted after first verification (one-time use).
    """
    now = datetime.now(timezone.utc)
    session = db.get(CaptchaSession, session_id)

    if session is None:
        return {"success": False, "correct_indices": [], "error": "Session not found."}
    if session.captcha_type != "grid":
        return {"success": False, "correct_indices": [], "error": "Wrong session type."}
    if session.expires_at.replace(tzinfo=timezone.utc) < now:
        db.delete(session)
        db.commit()
        return {"success": False, "correct_indices": [], "error": "Session expired."}

    payload = json.loads(session.captcha_answer)
    target = payload["target_category"]
    tiles = payload["tiles"]
    instruction = payload["instruction"]

    correct_indices = [
        i for i, tile in enumerate(tiles)
        if target in tile.get("categories", [])
    ]

    # Exact match required (order-independent)
    success = sorted(selected_indices) == sorted(correct_indices)

    # One-time use — delete regardless of success/failure
    db.delete(session)
    db.commit()

    return {
        "success": success,
        "correct_indices": correct_indices,
        "instruction": instruction,
    }
